apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bi-batch-rating-ui
  description: Rating Tool
  tags:
    - pricing circle
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
  annotations:
    backstage.io/source-template: template:default/springboot-template
spec:
  type: service
  lifecycle: sdlc
  owner: John Doe
  system: bi-batch-rating-tool
  dependsOn: ["resource:disruption-db"]
  apiConsumedBy: ["component:www-travelers"]
